language: objective-c
osx_image: xcode10.2

before_install:
- bundle install

install:
- pod repo update
- bundle exec pod install --verbose
- xcodebuild -workspace HybridRouteDemo.xcworkspace -scheme HybridRouteDemo -destination platform\=iOS\ Simulator,OS\=12.2,name\=iPhone\ X

cache:
- cocoapods
