language: objective-c
osx_image: xcode10.2
before_script:
  - pod repo update
script:
  - pod install
  - travis_retry xcodebuild archive -workspace HybridRouteDemo.xcworkspace -scheme HybridRouteDemo -archivePath ./HybridRouteDemo.xcarchive
