language: objective-c
osx_image: xcode10.2

xcode_workspace: HybridRouteDemo.xcworkspace
xcode_scheme: HybridRouteDemo
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X

podfile: ./podfile

before_install:
- bundle install

install:
  - pod repo update
  - pod install

cache:
  - cocoapods
